Singular-value decomposition

In [8]:
#defines a 3×2 matrix and calculates the Singular-value decomposition.

import numpy as np
from scipy.linalg import svd 

A=np.array([[1,2],[3,4],[5,6]])
print(A)

#svd
U,s,VT=svd(A)
print(U)
print(s)
print(VT)


[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
